config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  post 'windows/:id', to: 'windows#assign_user'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, :timeslots, :windows, :events
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]


# need to add nested resources for event/window http://guides.rubyonrails.org/routing.html#nested-resources

#Need to add admin namespace
      # namespace :admin do
      #   root to: "admin#index"
      # end
end

app/models/window.rb
class Window < ActiveRecord::Base

	belongs_to :event
	has_many :timeslots
	has_many :users, through: :timeslots

	# suggested validations:
	# validates_associated :event
	# validates :tasters, numerically: { less_than: :capacity }

# answer question "full?" returning nil if window.capacity not set
  def filled_up
  	if self.capacity
  		self.users.count >= self.capacity
  	else
  		nil
  	end
  end

# return available slot, return nil if full
  def get_slot
    unless filled_up || Event.find(self.event_id).filled_up
      self.timeslots.find { |slot| !slot.user }
    end
  end


  # def assign_user
  #   # target = get_slot
  #   get_slot.update(user_id: 1)
  # end

end

app/controllers/windows_controller.rb
class WindowsController < ApplicationController
  before_action :set_window, only: [:show, :edit, :update, :destroy]

  # GET /windows
  # GET /windows.json
  def index
    @windows = Window.all
  end

  # GET /windows/1
  # GET /windows/1.json
  def show
  end

  # GET /windows/new
  def new
    @window = Window.new
  end

  # GET /windows/1/edit
  def edit
  end

  # POST /windows
  # POST /windows.json
  def create
    @window = Window.new(window_params)

    if @window.save
      redirect_to @window, notice: 'Window was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /windows/1
  # PATCH/PUT /windows/1.json
  def update
    if @window.update(window_params)
      redirect_to @window, notice: 'Window was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /windows/1
  # DELETE /windows/1.json
  def destroy
    @window.destroy
    redirect_to windows_url, notice: 'Window was successfully destroyed.'
  end

  
  # POST /windows/:ID
  # How clunky is this DB success check? There's got to be a DRYer way to do this.
  def assign_user
    if !Window.find(params[:id]).filled_up && Window.find(params[:id]).get_slot.update_attributes(user_id: current_user.id)
      redirect_to events_url, notice: 'You got yourself a slot.'
    else
      redirect_to events_url, notice: 'You done fucked up.'
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_window
      @window = Window.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def window_params
      params.require(:window).permit(:event_id, :start_time, :duration, :capacity)
    end

end

app/helpers/windows_helper.rb
module WindowsHelper
end

app/views/windows/_form.html.erb
<%= form_for(@window) do |f| %>
  <% if @window.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@window.errors.count, "error") %> prohibited this window from being saved:</h2>

      <ul>
      <% @window.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :event_id %><br>
    <%= f.number_field :event_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.number_field :duration %>
  </div>
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/windows/edit.html.erb
<h1>Editing window</h1>

<%= render 'form' %>

<%= link_to 'Show', @window %> |
<%= link_to 'Back', windows_path %>

app/views/windows/index.html.erb
<h1>Listing windows</h1>

<table>
  <thead>
    <tr>
      <th>Event</th>
      <th>Start time</th>
      <th>Duration</th>
      <th>Capacity</th>
      <th>Full?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @windows.each do |window| %>
      <tr>
        <td><%= window.event_id %></td>
        <td><%= window.start_time %></td>
        <td><%= window.duration %></td>
        <td><%= window.capacity %></td>
        <td><%= window.filled_up %></td>
        <td><%= link_to 'Show', window %></td>
        <td><%= link_to 'Edit', edit_window_path(window) %></td>
        <td><%= link_to 'Destroy', window, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
        <% if window.timeslots %>
          <tr><td>Timeslots:<i>
            <% window.timeslots.each do |timeslot| %>
              <%= timeslot.id %>
            <% end %>
          </i></td></tr>
        <% end %>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Window', new_window_path %>

app/views/windows/new.html.erb
<h1>New window</h1>

<%= render 'form' %>

<%= link_to 'Back', windows_path %>

app/views/windows/show.html.erb
<p>
  <strong>Event:</strong>
  <%= @window.event_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @window.start_time %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @window.duration %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @window.capacity %>
</p>

<%= link_to 'Edit', edit_window_path(@window) %> |
<%= link_to 'Back', windows_path %>