config/routes.rb
Rails.application.routes.draw do

  root 'events#index'
  post 'windows/:id', to: 'windows#assign_user'
  get 'signup', to: 'users#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :users, :timeslots, :windows, :events
  resources :account_activations, only: :edit
  resources :password_resets, only: [:new, :create, :edit, :update]


# need to add nested resources for event/window http://guides.rubyonrails.org/routing.html#nested-resources

#Need to add admin namespace
      # namespace :admin do
      #   root to: "admin#index"
      # end
end

app/models/timeslot.rb
class Timeslot < ActiveRecord::Base

	belongs_to :window
	belongs_to :user

	# def filled_up(event)
	# 	Event.find(event).users.count >= Event.find(event).capacity
	# end

end

app/controllers/timeslots_controller.rb
class TimeslotsController < ApplicationController
  before_action :set_timeslot, only: [:show, :edit, :update, :destroy]

  # GET /timeslots
  # GET /timeslots.json
  def index
    @timeslots = Timeslot.all
  end

  # GET /timeslots/1
  # GET /timeslots/1.json
  def show
  end

  # GET /timeslots/new
  def new
    @timeslot = Timeslot.new
  end

  # GET /timeslots/1/edit
  def edit
  end

  # POST /timeslots
  # POST /timeslots.json
  def create
    @timeslot = Timeslot.new(timeslot_params)

    if @timeslot.save
      redirect_to @timeslot, notice: 'Timeslot was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /timeslots/1
  # PATCH/PUT /timeslots/1.json
  def update
    if @timeslot.update(timeslot_params)
      redirect_to @timeslot, notice: 'Timeslot was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /timeslots/1
  # DELETE /timeslots/1.json
  def destroy
    @timeslot.destroy
    redirect_to timeslots_url, notice: 'Timeslot was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_timeslot
      @timeslot = Timeslot.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def timeslot_params
      params.require(:timeslot).permit(:window_id, :user_id)
    end

end

app/helpers/timeslots_helper.rb
module TimeslotsHelper
end

app/views/timeslots/_form.html.erb
<%= form_for(@timeslot) do |f| %>
  <% if @timeslot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@timeslot.errors.count, "error") %> prohibited this timeslot from being saved:</h2>

      <ul>
      <% @timeslot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :window_id %><br>
    <%= f.number_field :window_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/timeslots/edit.html.erb
<h1>Editing timeslot</h1>

<%= render 'form' %>

<%= link_to 'Show', @timeslot %> |
<%= link_to 'Back', timeslots_path %>

app/views/timeslots/index.html.erb
<h1>Listing timeslots</h1>

<table>
  <thead>
    <tr>
      <th>Window</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @timeslots.each do |timeslot| %>
      <tr>
        <td><%= timeslot.window_id %></td>
        <td><%= timeslot.user_id %></td>
        <td><%= link_to 'Show', timeslot %></td>
        <td><%= link_to 'Edit', edit_timeslot_path(timeslot) %></td>
        <td><%= link_to 'Destroy', timeslot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Timeslot', new_timeslot_path %>

app/views/timeslots/new.html.erb
<h1>New timeslot</h1>

<%= render 'form' %>

<%= link_to 'Back', timeslots_path %>

app/views/timeslots/show.html.erb
<p>
  <strong>Window:</strong>
  <%= @timeslot.window_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @timeslot.user_id %>
</p>

<%= link_to 'Edit', edit_timeslot_path(@timeslot) %> |
<%= link_to 'Back', timeslots_path %>